name: Auto Update Branches

on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  update-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Update PRs
        uses: adRise/update-pr-branch@v0.7.2
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          base: 'main,master'
          required_approval_count: 0
          
      - name: Update branches with Copilot suggestions
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_BOT_TOKEN }}
          script: |
            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            
            for (const pr of pulls) {
              if (pr.mergeable_state === 'behind') {
                console.log(`Updating PR #${pr.number}: ${pr.title}`);
                
                try {
                  await github.rest.pulls.updateBranch({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number
                  });
                  
                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pr.number,
                    body: '🔄 Branch automatically updated with latest changes from base branch.'
                  });
                } catch (error) {
                  console.log(`Failed to update PR #${pr.number}: ${error.message}`);
                }
              }
            }
