name: Dependency Update

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_BOT_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Update npm dependencies
        if: hashFiles('package.json') != ''
        run: |
          npm update
          npm audit fix || true

      - name: Update Python dependencies
        if: hashFiles('requirements.txt') != ''
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt --upgrade

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_BOT_TOKEN || secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: update dependencies'
          body: |
            ## 🤖 Automated Dependency Update
            
            This PR updates all dependencies to their latest versions.
            
            ### Changes
            - Updated npm dependencies (if applicable)
            - Updated Python dependencies (if applicable)
            - Fixed security vulnerabilities
            
            ---
            *This PR was automatically generated by GitHub Actions*
          branch: automated/dependency-update
          delete-branch: true
          labels: |
            dependencies
            auto-merge
            auto-approve